---

- hosts: all 
  become: yes
  tasks:  
  
  - name: change permissions 
    file:
      path: "/home/{{user}}"
      state: directory
      owner: "{{user}}"
      group: "{{user}}"
      mode: '0766'

  - name: create a .ssh folder
    file:
      path: "/home/{{user}}/.ssh"
      state: directory
      owner: "{{user}}"
      group: "{{user}}"
      mode: '0766'

  - name: add file authorized_keys
    file:
      path: "/home/{{user}}/.ssh/authorized_keys"
      state: touch
    tags: authorized_keys 

    
  - name: put devel pubkey to authorized keys
    lineinfile:
      path: "/home/{{user}}/.ssh/authorized_keys"
      line: "{{pubkey}}"
      state: present
    tags: pubkey

  - name: copy pubkey, set owner and permissions
    become: yes
    copy:
      src: ~/.ssh/id_rsa_github_deployment
      dest: "/home/{{user}}/.ssh/id_rsa"
      owner: "{{user}}"
      group: "{{user}}"
      mode: '0600'
    tags: copykey

  - name: create a storage folder
    file:
      path: "/home/{{user}}/{{storage_folder}}"
      state: directory
      mode: '0755'

  - name: create a frontend folder
    file:
      path: "/home/{{user}}/{{frontend_folder}}"
      state: directory
      mode: '0755'

